In [3]:
import numpy as np

# (a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

# (b) Flatten the NumPy array
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten())
print(array1.ravel())

# (c) Compare two NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))
print(arr1 == arr2)

# (d) Most frequent value and indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(x).argmax(), np.where(x == np.bincount(x).argmax()))
print(np.bincount(y).argmax(), np.where(y == np.bincount(y).argmax()))

# (e) Matrix sums
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis=1))
print(np.sum(gfg, axis=0))

# (f) Matrix properties
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
vals, vecs = np.linalg.eig(n_array)
print(vals)
print(vecs)
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

# (g) Matrix multiplication and covariance
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.matmul(p, q))
print(np.cov(p, q))

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.matmul(p, q))
print(np.cov(p.T, q))

# (h) Inner, outer, cartesian product
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
print(np.kron(x, y))


[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
True
[[ True  True]
 [ True  True]]
1 (array([0, 5, 7, 8, 9], dtype=int64),)
1 (array([0, 1, 2], dtype=int64),)
45
[[14]
 [16]
 [15]]
[[20  9 16]]
176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001
[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]
[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2 10  0  3 15  0

In [5]:
import numpy as np

# (a) For the array
array = np.array([[1, -2, 3],[-4, 5, -6]])

# (i) Element-wise absolute value
print(np.abs(array))

# (ii) Percentiles of flattened, column-wise, row-wise
print(np.percentile(array, [25, 50, 75]))          # flattened
print(np.percentile(array, [25, 50, 75], axis=0))  # per column
print(np.percentile(array, [25, 50, 75], axis=1))  # per row

# (iii) Mean, Median, Standard Deviation
print(np.mean(array), np.median(array), np.std(array))                # flattened
print(np.mean(array, axis=0), np.median(array, axis=0), np.std(array, axis=0))  # columns
print(np.mean(array, axis=1), np.median(array, axis=1), np.std(array, axis=1))  # rows

# (b) For array a
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor
print(np.floor(a))

# Ceiling
print(np.ceil(a))

# Truncated
print(np.trunc(a))

# Rounded
print(np.round(a))


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [7]:
import numpy as np

# (a) For the array
array = np.array([10, 52, 62, 16, 16, 54, 453])

# (i) Sorted array
print(np.sort(array))

# (ii) Indices of sorted array
print(np.argsort(array))

# (iii) 4 smallest elements
print(np.partition(array, 3)[:4])

# (iv) 5 largest elements
print(np.partition(array, -5)[-5:])

# (b) For the array
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i) Integer elements only
print(array[array == array.astype(int)])

# (ii) Float elements only
print(array[array != array.astype(int)])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[16 10 16 52]
[ 16  52  62  54 453]
[1. 2. 3. 2.]
[1.2 2.2]


In [15]:
from PIL import Image
import numpy as np

def img_to_array_gray(path):
    img = Image.open(path).convert("L")   
    arr = np.array(img)
    np.savetxt("image_gray.txt", arr, fmt="%d")   
    return arr

gray = img_to_array_gray("C:/Users/kanav/OneDrive/Desktop/whop.jpg")   

gray = img_to_array_gray("myphoto.png")


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kanav\\myphoto.png'